### ISSUE TITLE
Plan export, project number in exported file

### ISSUE THREAD

**Issue by vbhavdal** [hmpf/easydmp#190]
To support Marius' work, 
propose "(project number)-(PK).pdf"

Discuss.

**Comment by hmpf** [comment]
We could have a specialized export script for this round's RFK that knows how to extract the project number from the project number answer, given that the template is the RFK-spesific one.

As for the future, with tags we can tag a question "this is a project number" and look up the tags instead of questions.

**Comment by hmpf** [comment]
I made a script tailored for this round, closing this issue.
