### ISSUE TITLE
Hosted DMP

### ISSUE THREAD

**Issue by mpejcoch** [hmpf/easydmp#226]
Currently it is only possible to export the DMP to a static PDF or HTML only available to the user currently logged in. It would be great if we could get a permalink to a hosted version of the DMP, which could be linked to from other places, such as metadata entries or project documentation.

**Comment by hmpf** [comment]
What do you mean by "hosted"?

It is possible to store a doi on a plan, (well, that field can be used for anything as there's no validation), but there is no process around setting it since nobody can agree on one. (Same reason the role of the "published"-flag has mostly been taken over by the "locked"-flag, there's no agreement on what publishing a dmp entails, so no process can be specced and built. There isn't agreement on which permalink system should be used even: "doi" was just the first mentioned.)

Would it be sufficient to make the doi-field or something similar available, to be filled whenever the editors feel like it?

**Comment by mpejcoch** [comment]
I meant that e.g. my https://easydmp.sigma2.no/plan/1307/ could be made visible to the whole world in its rendered html form and that the URL would be permanent, so that I could use it in a project application directly.

**Comment by hmpf** [comment]
The url is permanent (unless the site is moved to a different domain) and the document-like html-version of plans used to be readable to all by default, but this was unwanted by some other users of EasyDMP that insisted on only logged-in users having access. Would something like a flag marking a plan as "public" do?

**Comment by mpejcoch** [comment]
> Would something like a flag marking a plan as "public" do?

Yes, that would work I think.

**Comment by hmpf** [comment]
Blocked by: The auditlog assumes actors are logged in users and cannot log acts from AnonymousUser.

**Comment by hmpf** [comment]
If the object sent in as an actor to the auditlog lacks a primary key (which holds for the default AnonymousUser), the log is no longer attempted.

**Comment by hmpf** [comment]
Closed by 995548001bfb1de676ba5c847097cab8bea0c60d
