### ISSUE TITLE
500 server error when deleting a plan

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#29]
When I try to delete a plan I get a server 500 error after confirming the delete. This is for the review easydmp.

**Comment by hmpf** [comment]
I've been working on this today. Remember when the sections and questions of the H2020 template disappeared? Well, if you haven't gotten that error today, those sections and questions would have disappeared again, as your 500 was triggered by not being allowed to erase the sections and questions.

Meaning: most likely, the reason for the disappearance last time was a bug in the code, and that bug is now possibly fixed on the test-server. I'm not planning to remove the manual paranoia GRANTs in the DB yet though.
