### ISSUE TITLE
Problems updating a response to a question

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#49]
In the production easyDMP when a user tries to make a change to an existing response in a data management plan the changes are not 'saved'. If the user goes to the plan summary and then views the response they see that the changes are missing.

**Comment by hmpf** [comment]
This behaved differently on different deployments.

Fix, in short:

* Use python 3.7 because its dicts are ordered, last in goes last.
* Ensure that all keys are strings, because JSON converts int keys to strings, and may allow duplicate keys.
* Different JSON libraries treat duplicate keys differently. Python's `json` picks the last key if there are duplicates, and with python 3.7, the last key is always the newest key.

**Comment by hmpf** [comment]
Fix deployed in version 0.14.5.
