### ISSUE TITLE
Problem with the graph PDF file in the Administration DPMT->Section page

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#98]
As an admin, if I click on the DMPT and then the Sections button I get a list of sections. If I click on a section for the RFK2020T template and I click on the PDF button in the Graph column I get a error message "Error: Failed to load PDF document".

**Comment by hmpf** [comment]
.. this unfortunately doesn't work well on production due to more than one replica. The files are cached on disk. There are n "disk"s when there are n replicas, not a shared disk. 

Staging has only one replica, that should do as a workaround.

Worse: there seems to be a cache-invalidation problem: they are not updated at the correct time and therefore outdated.

```
There are only two hard problems in software development:

1. Naming
2. Cache invalidation
3. Off-by-one errors
```
See https://martinfowler.com/bliki/TwoHardThings.html for more of those.

This is a case of 2.

**Comment by vbhavdal** [comment]
I suggest to remove caching of PDF and generate them on the fly each time.

**Comment by hmpf** [comment]
Related: #99.

**Comment by hmpf** [comment]
Ah. The reason a file is stored locally is because the library used, [Graphviz](https://pypi.org/project/graphviz/) **render**s to a file  or **pipe**s to a pipe. There is no option to render to bytes or IOStream, and it is not possible to send in a file object instead of a filename. There are two other graphviz libraries however: [PyGraphviz](https://pypi.org/project/pygraphviz/) and [pydot](https://pypi.org/project/pydot/). One of those might be able to skip going by a file.

**Comment by hmpf** [comment]
The reason for "going via a file" is that every library talks with either a binary executable or a binary. `pydot` saves a temporary file which is then read back in, while `graphviz` has a `pipe()`-method that needs investigating.
